### ISSUE TITLE
syslog has no method 'on'

### ISSUE THREAD

**Issue by royalgarter** [bloodhound/syslog-stream#5]
I want to listen for the syslog and using your example but facing this problem when running.

Please help if possible, thank you.

``` javascript
// My code
_syslog.on('log', function (message, severity) {
    if (message.indexOf('TESTING') < 0)
        console.log('TESTING', message, severity);
});

// Exception when running
TypeError: Object function Syslog(identity, facility) {
  this.identity = identity || 'node';
  this.facility = facility || 'user';
  this.severity = 'debug';
  // Open connection to syslog
  connected = syslog.open(this.identity, this.facilities[this.facility] * 8);
  // Call parent constructor
  stream.Writable.call(this, { decodeStrings: false });
} has no method 'on'
    at ReadStream.Readable.pipe (_stream_readable.js:478:8)
    at Object.<anonymous> (/app/api.js:917:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by alexmingoia** [comment]
Are you constructing a new instance with `new`? Either way I've updated it to not require the new keyword.

``` javascript
var Syslog = require('syslog-stream');

var logger = new Syslog(); // any version

var logger = Syslog(); // version >= 1.3.0
```

**Comment by royalgarter** [comment]
Thank you, it's working now :+1:
